//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   변경사항 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Apply {
            get {
                return ResourceManager.GetString("String_Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   목록 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Clear_List {
            get {
                return ResourceManager.GetString("String_Btn_Clear_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Extension_Change {
            get {
                return ResourceManager.GetString("String_Btn_Extension_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Extension_Delete {
            get {
                return ResourceManager.GetString("String_Btn_Extension_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Load {
            get {
                return ResourceManager.GetString("String_Btn_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Name_Add {
            get {
                return ResourceManager.GetString("String_Btn_Name_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Name_Clear {
            get {
                return ResourceManager.GetString("String_Btn_Name_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 변경
        ///(특정 위치)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Name_Clear_Ext {
            get {
                return ResourceManager.GetString("String_Btn_Name_Clear_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번호 붙이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Num_Add {
            get {
                return ResourceManager.GetString("String_Btn_Num_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자릿수 맞추기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Num_Fix {
            get {
                return ResourceManager.GetString("String_Btn_Num_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원래대로 복구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_Restore {
            get {
                return ResourceManager.GetString("String_Btn_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택항목 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_SelectItem_Del {
            get {
                return ResourceManager.GetString("String_Btn_SelectItem_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택항목 아래로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_SelectItem_Down {
            get {
                return ResourceManager.GetString("String_Btn_SelectItem_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택항목 위로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Btn_SelectItem_Up {
            get {
                return ResourceManager.GetString("String_Btn_SelectItem_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 {0}에 번호를 붙입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Label_AddNumber {
            get {
                return ResourceManager.GetString("String_Label_AddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일에 이름을 추가합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Label_FormType_AddName {
            get {
                return ResourceManager.GetString("String_Label_FormType_AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일의 앞쪽에 이름을 추가합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Label_FormType_AddNameFront {
            get {
                return ResourceManager.GetString("String_Label_FormType_AddNameFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일의 확장자를 변경합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Label_FormType_ChangeExtension {
            get {
                return ResourceManager.GetString("String_Label_FormType_ChangeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_CreateTime {
            get {
                return ResourceManager.GetString("String_List_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_CurName {
            get {
                return ResourceManager.GetString("String_List_CurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_FilePath {
            get {
                return ResourceManager.GetString("String_List_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_FileSize {
            get {
                return ResourceManager.GetString("String_List_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_FullPath {
            get {
                return ResourceManager.GetString("String_List_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_ModifyTime {
            get {
                return ResourceManager.GetString("String_List_ModifyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꿀 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_List_ReName {
            get {
                return ResourceManager.GetString("String_List_ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번호 붙이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Title_AddNumber {
            get {
                return ResourceManager.GetString("String_Title_AddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Title_FormType_AddName {
            get {
                return ResourceManager.GetString("String_Title_FormType_AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 추가(앞)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Title_FormType_AddNameFront {
            get {
                return ResourceManager.GetString("String_Title_FormType_AddNameFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 확장자 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Title_FormType_ChangeExtension {
            get {
                return ResourceManager.GetString("String_Title_FormType_ChangeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상 문자열과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_TItle_NameForm_Title1 {
            get {
                return ResourceManager.GetString("String_TItle_NameForm_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꿀 문자열과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Title_NameForm_Title2 {
            get {
                return ResourceManager.GetString("String_Title_NameForm_Title2", resourceCulture);
            }
        }
    }
}
